## Linear Equations

Lets take a linear system of equations in $R^2$  
- $2x + 3y = 8$  
- $x + 6y = 13$
   
   
* Each equation represent a line.
* The combination of the 2 equations represent a point.

* In $R^2$  
    * 1 Equation represent a Line.
    * Need atleast 2  equations to represent a Point.     
    

* In $R^3$  
    * 1 Equation represent a Plane.
    * Need atleast 2 equations to represent a Line.
    * Need atleast 3 equations to represent a Point.

#### Row Picture 
Row picture is the graphical representation of what a linear system of equations actually represents.  
Example-  
- $2x + 3y = 8$  
- $x + 6y = 13$  

Row picture of the above set of equations-  
$(2\hspace{2mm} 3)\cdot(x\hspace{2mm} y)=8$  
$(1\hspace{2mm} 6)\cdot(x\hspace{2mm} y) = 13$

#### Column Picture  
Column Picture is a way of representing linear system of equations using column vectors.  
Example-  
- $2x + 3y = 8$  
- $x + 6y = 13$  
  
Column picture of the above system of equation-  
$\begin{bmatrix} 2\\1 \end{bmatrix}x + \begin{bmatrix} 3\\6 \end{bmatrix}y = \begin{bmatrix} 8\\13 \end{bmatrix}$  
  
    
Above can also be represented using Matrix notation,  
$\begin{bmatrix} 2 & 3\\1 & 6 \end{bmatrix} \begin{bmatrix} x\\y \end{bmatrix} = \begin{bmatrix} 8\\13 \end{bmatrix}$

Set of Equations in $R^3$,  
- $x + 3y + 8z = 20$  
- $3x + 6y + 5z = 16$
- $5x + 15y + 3z = 5$  
  
  
Column picture of th above using Matrix notation  
$\begin{bmatrix} 1 &3&8\\3 & 6&5\\5&15&3 \end{bmatrix} \begin{bmatrix} x\\y\\z \end{bmatrix} = \begin{bmatrix} 20\\16\\5 \end{bmatrix}$

Column picture of system of equations in $R^n$  
* $A_{e\times n}~~x_n = b_e$  
    
    
* $A_{e\times n}$ : coefficient matrix of the system of n-variable linear equations.

### Solving Linear Equation using column picture   
Steps:  
* Elimination (forward process) 
* Substitution (backward process)

In [20]:
# Algorithm  
import numpy as np

M= np.array([[1,3,8],[3,6,5],[5,15,3]]) ## example matrix
S = np.array([[20],[16],[5]]) ## solution vector
##print('column picture - ')
##print(M,'*',np.array(['x','y','z']),'=',S)

#------Elimination--------
for row_n in range(len(M)-1):
    pivot = M[row_n][row_n]
    row =  M[row_n]
    #print(pivot)
    for row_e in range(row_n+1,len(M)):
        c = M[row_e][row_n]   ## first non-zero elements in a row
        M[row_e] = M[row_e] - (c*row/pivot)
    print(M)


[[  1   3   8]
 [  0  -3 -19]
 [  0   0 -37]]
[[  1   3   8]
 [  0  -3 -19]
 [  0   0 -37]]


### Elimination

**Operations in elimination**:
* Row operation
* Row exchange

  
**Outcome of elimination**

For nxn linear system of equations:
* Elimination leads to a upper triangular matrix
* Pivots - first non-zero elements in a row of the resulting matrix
  
  
**Possible types of Solution**  
* if the resulting matrix has n pivots in the diagonal,  
the system of equation is **Non-Singular** and has **Unique solution**.  
  
    
* if the resulting matrix does not have n pivots in the diagonal,
the system of equation is **Singular**.
    * If the system of equation is inconsitent - **No Solution**.  
     Occurs when, the row in ceofficcient matrix which does not have a pivot, the same row in $b$ vector contains non-zero element.
    * If the system of equation is consitent - **Infinite number of Solution**.  
      Occurs when, the row in ceofficcient matrix which does not have a pivot, the same row in $b$ vector contains zero.  
  
  
Elimination complexity:
* row operation - $O(n^2)$
* All Floating point operations - $O(n^3)$

### Substitution

b

## LU Factorization

Let $nxn$ linear system of equations be  
$Ax=b$.  


After performing all elementary row operation on $A$ we get a Upper Triangular Matrix $U$.  
$E_3E_2E_1 A = U$  
  
Also,  
$E_2^{-1}E_2^{-1}E_3^{-1}E_3E_2E_1 A = E_2^{-1}E_2^{-1}E_3^{-1} U$  
or, $A = E_2^{-1}E_2^{-1}E_3^{-1} U$  
  
Since inverse of Elementary matrix is Lower triangular and product of lower triangular is also lower triangular,  
we can write $E_2^{-1}E_2^{-1}E_3^{-1}$ as $L$.  
  
$\rightarrow A = LU$  
$\therefore$ we can factorize any coefficient matrix into lower triangular matrix $L$ and upper triangular matrix $U$,

Now, we can rewrite our $nxn$ linear system of equations  
$Ax=b$, as  
$LUx = b$. We can discard $A$ now.

#### Solving for $x$.  
  
$LUx = b$  
$\rightarrow Ux=L^{-1}b$  
  
let,$L^{-1}b = c$  
$\rightarrow b=Lc$  
  
Therefore, Three steps to solution:
1. Factor $A=LU$
2. Solve $Lc=b$ < forward substitution > < order $O(n^2)$ >
3. Solve $Ux=c$  < backward substitution > < order $O(n^2)$ >

We want to make the diagonal elements of $U$ 1.  
So, we perform $R_i \leftarrow p_i$ row operatons on all row, $p_i$ denotes the diagonal element in row $i$.  
    
Then, $U$ can be also written as  
$U = DU^{'}$  
$D$ contains pivots on its diagonal and zeroes elsewhere.  
  
Therefore, now  
$A=LDU^{'}$


    Solving system of equations using LU factorization does not work always. It fails when there is a row exchange operation in elimination phase.

#### Permutation matrix $P$ 
Permutation matrix $P$ is obtained by performing any number of row exchanges among the rows of an Identity matrix $I$.  
  
Some properties of $P$:  
* $P$ has same rows as $I$.
* Product of any permutation matrix $P_1$ and $P_2$ is also a permutation matrix $P_3$.
* $P^{-1} = P^T$  
* Using a $nxn$ matrix, we can obtain $n!$ number of Premutation matrix.
  
Permutation matrix can represent row exchange operation.  
So, when a permutation matrix used as elementary matrix and premultiplied to $A$, results in row exchnage of $A$.
  
Therefore, coefficient matrix $A$ can be seen as  
$LDU^{'}=PA$